sudo: required

services:
  - docker

language: java

cache:
  directories:
    - $HOME/.m2

dist: trusty

jdk:
  - openjdk8

script: 
  - mvn cobertura:cobertura
  - mvn -P release-profile clean install
  - mvn -P integration-tests verify

after_success:
- bash <(curl -s https://codecov.io/bash)