sudo: required

services:
  - docker

language: java

cache:
  directories:
    - $HOME/.m2

dist: trusty

jdk:
  - openjdk8

script: 
  - mvn -P release-profile clean install
  - mvn -P integration-tests verify