sudo: required

services:
  - docker

language: java

cache:
  directories:
    - $HOME/.m2

dist: trusty

jdk:
  - openjdk8

script: 
  - mvn clean install -P release-profile
  - mvn clean install -P integration-tests