sudo: required
services:
  - docker
language: java
cache:
  directories:
    - $HOME/.m2
dist: trusty
jdk:
  - openjdk8

jobs:
  include:
    - stage: test
      if: type = pull_request
      script: 
        - mvn -P release-profile clean install
        - mvn -P integration-tests verify
        - mvn -P integration-tests cobertura:cobertura-integration-test
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      if: type = push AND branch = master AND tag IS present
      script: mvn site
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: target/site/
        github_token: $site_token
        on:
          tags: true
          branch: master
